/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include<stdio.h>
#include<stdlib.h>
#include<string.h>

#include "selec.h"


void
selprog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char *result_1;
	char *fil_1_arg;
	enum clnt_stat retval_2;
	char *result_2;
	listt  rev_1_arg;
	enum clnt_stat retval_3;
	char *result_3;
	listt  enc_1_arg;
	enum clnt_stat retval_4;
	char *result_4;
	listt  del_1_arg;
	enum clnt_stat retval_5;
	char *result_5;
	list  conc_1_arg;
	char name[100];
        char temp[1000] = "\0";
        char tempp[1000] = "\0";
        char encc[100];
        char fname[100];
        char conct[100];
        char concct[100];
        int select = 0;
	int MAXSIZ = 10000;
#ifndef	DEBUG
	clnt = clnt_create (host, SELPROG, SELVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("1.User 2.Reverse 3.Encrypt 4.Delete 5.Concatenation\n");
        printf("Enter the operation number you want to perform:");
        scanf("%d",&select);

        switch(select) //This statement lets user select only one option
        {
        // prints the number of users logged  onto the client
        case 1:
        //invokes the method fil_1_arg on the server and stores the result onto result_1
	result_1 = malloc(MAXSIZ);
	retval_1 = fil_1((void*)&fil_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) 
	{
		clnt_perror (clnt, "call failed");
	}
	else
        {
        printf("%s\n",result_1); //prints the result_1 onto the client
	}
        break;
        // reverses the string entered and prints onto the client
         case 2:
         printf("Enter the string:"); //prompts the user to enter the string 
         scanf("%s",name); // Takes the input and stores it into name
         scanf("%[^\n]%*c", temp); // Takes string with spaces till new line
         strcat(name,temp); // concatenate both forming the complete string 
         rev_1_arg.st = name; // To access the string st present in  struct  
         printf("The string entered:%s\n", rev_1_arg);
	 result_2 = malloc(MAXSIZ);
	 retval_2 = rev_1(&rev_1_arg, &result_2, clnt);
	 if (retval_2 != RPC_SUCCESS) 
	 {
		clnt_perror (clnt, "call failed");
	 }
	else
        {
        printf("The string reversed:%s\n",result_2);
	free(result_2);
	}
        break;
        // Encrypts the string entered by the user and printts onto the client
        case 3:
         printf("Enter the string for Encryption:");//prompts the user to enter the string
         scanf("%s",&encc);// Takes the input and stores it into encc
         scanf("%[^\n]%*c", temp); // Takes string with spaces till new line
         strcat(encc,temp);
         enc_1_arg.st = encc;
         printf("The string entered: %s\n", enc_1_arg);
	 result_3 = malloc(MAXSIZ);
	 retval_3 = enc_1(&enc_1_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	else
        {
        printf("The encrypted string:%s\n",result_3);
        free(result_3);        
	}
        break;
        // Deletes the file if present and prints the message
       case 4:
        printf("Enter the file name:");
        scanf("%s",&fname);
        del_1_arg.st = fname;
	result_4 = malloc(MAXSIZ);
	retval_4 = del_1(&del_1_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS)
	{
		clnt_perror (clnt, "call failed");
	}
	else
        {
        printf("%s\n",result_4);      
	free(result_4);
	}
        break;
        // Concatenates two strings
       case 5:
        printf("Enter the first string:");
        scanf("%s",&conct);
        scanf("%[^\n]%*c", temp);
        strcat(conct,temp); //concatenates two strings
        conc_1_arg.str = conct;
        printf("Enter the second string:");
        scanf("%s",&concct);
        scanf("%[^\n]%*c", tempp);
        strcat(concct,tempp);
	conc_1_arg.strr = concct;
        result_5 = malloc(MAXSIZ);	
	retval_5 = conc_1(&conc_1_arg, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	else
        {
        printf("The concatenation of the strings:%s\n",result_5);
        free(result_5);
	}
        break;
        default:
         printf("Invalid Input\n");
        }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	selprog_1 (host);
exit (0);
}
