/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "selec.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
fil_1(void *argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, fil,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rev_1(listt *argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, rev,
		(xdrproc_t) xdr_listt, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
enc_1(listt *argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, enc,
		(xdrproc_t) xdr_listt, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
del_1(listt *argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, del,
		(xdrproc_t) xdr_listt, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
conc_1(list *argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, conc,
		(xdrproc_t) xdr_list, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}
